### ISSUE TITLE
FORGE_SERVER description

### ISSUE THREAD

**Issue by mgkimsal** [mehrancodes/veyoze#24]
Is this the 'name' (like 'breezy-hurricane' or whatever random name forge might assign)?  Or an IP address?  Or something else?

**Comment by mgkimsal** [comment]
So... setting the FORGE_SERVER to the IP of the forge server in question, I still get

```
Laravel\Forge\Exceptions\NotFoundException 

  The resource you are looking for could not be found.
```

I can't get much useful debugging from github action runners, but it is in the FindServer code

composer/vendor/mehrancodes/veyoze/app/Services/Forge/Pipeline/FindServer.php(30): Laravel\\Forge\\Forge->server()

**Comment by mgkimsal** [comment]
The 'FORGE_SERVER' needs to be the server's ID in Forge (54183, for example - can get from the URL if nothing else)

So.. now it can't make a site.   Still digging through

```
 INFO    Start finding the server.
  INFO    Finding the associated site.
  INFO    ---> Site not found.
  INFO    Creating a new site.
  INFO    ---> Enabling site isolation.
[2023-10-20 17:53:26] development.ERROR: The given data failed to pass validation. {"exception":"[object] (Laravel\\Forge\\Exceptions\\ValidationException(code: 0): The given data failed to pass validation. at /composer/vendor/laravel/forge-sdk/src/MakesHttpRequests.php:106)
```

**Comment by mehrancodes** [comment]
Thanks for addressing this issue on the https://github.com/mehrancodes/veyoze/issues/25.

I'm considering refining the documentation this week. Additionally, I'll be working on improving the clarity of error messages for better troubleshooting.

Also you can refer to this [working sample for Laravel](https://github.com/mehrancodes/veyoze-laravel-sample/tree/main/.github/workflows) that includes two workflows for provision and teardown processes.

**Comment by mehrancodes** [comment]
@mgkimsal, could you please review [my recent PR focused](https://github.com/mehrancodes/veyoze/pull/31) on enhancing `Forge ValidationException` error clarity? Which is related to this issue. I'd appreciate your insight and am open to adding you as a contributor.

**Comment by mehrancodes** [comment]
Check out the [latest release](https://github.com/mehrancodes/veyoze/releases/tag/v0.0.6)! Please try the provision command again to help pinpoint the issue with the Forge Site creation. 🛠️
