### ISSUE TITLE
Timeout broke something...

### ISSUE THREAD

**Issue by mgkimsal** [mehrancodes/veyoze#32]
Cannot assign string to property App\Services\Forge\ForgeSetting::$timeoutSeconds of type int

I was not seeing this yesterday when running from my local env, only now in a GH action.  Apologies for the mistake.

**Comment by mehrancodes** [comment]
Absolutely! Keeping the keys as strings offers flexibility to use both integers and strings as needed. 👍

**Comment by mgkimsal** [comment]
Thanks.  From a type-point-of-view, it really is an integer, but didn't want to overcomplicate the setting process with types.  I'll test this again.  Thanks!
